services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-vol:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payments-net

  migration:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payments-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payments-net

  topology:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python -m payments_processor.messaging
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - payments-net

  api:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:80"
    restart: unless-stopped
    command: uvicorn payments_processor.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src/payments_processor:/app/src/payments_processor
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
      topology:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    networks:
      - payments-net

  outbox-dispatcher:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    command: python -m payments_processor.outbox_dispatcher.main
    volumes:
      - ./src/payments_processor:/app/src/payments_processor
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      topology:
        condition: service_completed_successfully
    networks:
      - payments-net

volumes:
  postgres-vol:
    driver: local
  rabbitmq-vol:
    driver: local

networks:
  payments-net:
    driver: bridge
