class PaymentsConstants:
    AMOUNT_MAX_DIGITS = 20
    AMOUNT_DECIMAL_PLACES = 4
    DESCRIPTION_MAX_LEN = 1000
    IDEMPOTENCY_KEY_MAX_LEN = 255
    WEBHOOK_URL_MAX_LEN = 2048

    OUTBOX_AGGREGATE_TYPE_MAX_LEN = 64
    OUTBOX_EVENT_TYPE_MAX_LEN = 128
    OUTBOX_ROUTING_KEY_MAX_LEN = 128
